2025-02-17 03:14:01 - WARNING - Retrying (Retry(total=6, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='deployment-sofftlsf9z4fya3qchykaanq.stag-vxzy.zettablock.com', port=443): Read timed out. (read timeout=90)")': /main
2025-02-17 03:15:36 - WARNING - Retrying (Retry(total=5, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='deployment-sofftlsf9z4fya3qchykaanq.stag-vxzy.zettablock.com', port=443): Read timed out. (read timeout=90)")': /main
